spring:
  jpa:
    hibernate:
      ddl-auto: update      # jamais 'update' en prod — utilise Flyway sinon
    show-sql: false

  datasource:
    url:      ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

app:
  jwt:
    secret:     ${APP_JWT_SECRET}
    expiration: ${APP_JWT_EXPIRATION}

logging:
  level:
    com.jobtracker: INFO
    org.hibernate:  WARN