spring:
  application:
    name: job-tracker-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/jobtracker
    username: ${DB_USERNAME:jobtracker}
    password: ${DB_PASSWORD:jobtracker}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update        # create-drop en test, update en dev, none en prod
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  jackson:
    default-property-inclusion: non_null   # les champs null n'apparaissent pas dans le JSON

server:
  port: 8080

logging:
  level:
    com.jobtracker: DEBUG

app:
  jwt:
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expiration: 86400000   # 24h en ms